# Development Profile Configuration
# Activated with: --spring.profiles.active=dev or SPRING_PROFILES_ACTIVE=dev

spring:
  application:
    name: ${APP_NAME:comprehensive-dev-portal}
  
  # Database Configuration - PostgreSQL for Development
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devportalkirostart}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    
    # Connection Pool Configuration (HikariCP)
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:20}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      idle-timeout: ${DB_POOL_IDLE_TIMEOUT:300000}
      connection-timeout: ${DB_POOL_CONNECTION_TIMEOUT:20000}
      max-lifetime: ${DB_POOL_MAX_LIFETIME:1200000}
      leak-detection-threshold: ${DB_POOL_LEAK_DETECTION:60000}
      pool-name: "HikariCP-DevPortal-Dev"
      connection-test-query: "SELECT 1"
    
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: ${JPA_SHOW_SQL:true}
    format-sql: ${JPA_FORMAT_SQL:true}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: ${JPA_BATCH_SIZE:25}
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: ${JPA_FETCH_SIZE:16}
        connection:
          provider_disables_autocommit: true
        enable_lazy_load_no_trans: false
        generate_statistics: true
      
  # Security Configuration
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:admin123}
      roles: ${SECURITY_USER_ROLES:ADMIN}
      
  # Cache Configuration
  cache:
    type: ${CACHE_TYPE:caffeine}
    caffeine:
      spec: ${CACHE_SPEC:maximumSize=1000,expireAfterWrite=10m,expireAfterAccess=5m}
    cache-names:
      - learningModules
      - learningStats
      - userProgress
      - interviewQuestions
    
  # Development Tools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Server Configuration
server:
  port: ${SERVER_PORT:3008}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}
    
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always}
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
      
# Logging Configuration
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.learningportal: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework.security: ${LOGGING_LEVEL_SECURITY:DEBUG}
    org.hibernate.SQL: ${LOGGING_LEVEL_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_SQL_PARAMS:TRACE}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: ${LOGGING_FILE:logs/dev-application.log}
    max-size: ${LOGGING_FILE_MAX_SIZE:10MB}
    max-history: ${LOGGING_FILE_MAX_HISTORY:30}
    
# Custom Application Properties
app:
  name: Comprehensive Developer Portal
  version: 1.0.0
  description: The most comprehensive learning portal for Java, Spring, React, and System Design
  environment: development
  
  # Performance Monitoring
  performance:
    monitoring-enabled: ${PERFORMANCE_MONITORING_ENABLED:true}
    slow-query-threshold: ${PERFORMANCE_SLOW_QUERY_THRESHOLD:1000}
    request-timeout: ${PERFORMANCE_REQUEST_TIMEOUT:30000}
  
  # Feature Flags
  features:
    code-execution: ${FEATURE_CODE_EXECUTION:true}
    ai-assistance: ${FEATURE_AI_ASSISTANCE:true}
    progress-analytics: ${FEATURE_PROGRESS_ANALYTICS:true}
    social-features: ${FEATURE_SOCIAL_FEATURES:false}
