# Production Profile Configuration
# Activated with: --spring.profiles.active=production or SPRING_PROFILES_ACTIVE=production
# All sensitive values MUST be provided via environment variables in production

spring:
  application:
    name: ${APP_NAME:senior-dev-academy}
  
  # PostgreSQL Database Configuration - Fully Externalized
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devacademykiro}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}  # REQUIRED: Must be set via environment variable
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    
    # Connection Pool Configuration (HikariCP) - Externalized
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:20}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      idle-timeout: ${DB_POOL_IDLE_TIMEOUT:300000}
      connection-timeout: ${DB_POOL_CONNECTION_TIMEOUT:20000}
      max-lifetime: ${DB_POOL_MAX_LIFETIME:1200000}
      leak-detection-threshold: ${DB_POOL_LEAK_DETECTION:60000}
      pool-name: "HikariCP-DevPortal-Prod"
      
  # JPA/Hibernate Configuration for PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}  # Use validate in production, never create-drop
    show-sql: ${JPA_SHOW_SQL:false}  # Disable SQL logging in production
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        # Enable batch processing for better performance
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        # Enable second-level cache
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
            
  # Security Configuration - REQUIRED environment variables
  security:
    user:
      name: ${SECURITY_USER_NAME}  # REQUIRED: Must be set via environment variable
      password: ${SECURITY_USER_PASSWORD}  # REQUIRED: Must be set via environment variable
      roles: ${SECURITY_USER_ROLES:ADMIN}
      
  # Cache Configuration (Redis in production) - Externalized
  cache:
    type: ${CACHE_TYPE:redis}
    redis:
      time-to-live: ${CACHE_TTL:600000}  # 10 minutes default
      
  # Redis Configuration - Externalized
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: ${REDIS_TIMEOUT:2000ms}
    jedis:
      pool:
        max-active: ${REDIS_POOL_MAX_ACTIVE:8}
        max-idle: ${REDIS_POOL_MAX_IDLE:8}
        min-idle: ${REDIS_POOL_MIN_IDLE:0}

# Server Configuration
server:
  port: ${SERVER_PORT:3008}
  servlet:
    context-path: /api
  # Enable compression
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  # SSL Configuration (uncomment for HTTPS)
  # ssl:
  #   key-store: classpath:keystore.p12
  #   key-store-password: ${SSL_PASSWORD:password}
  #   key-store-type: PKCS12
  #   key-alias: tomcat
    
# Actuator Configuration (Production monitoring)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
        
# Logging Configuration for Production - Externalized
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.learningportal: ${LOGGING_LEVEL_APP:INFO}
    org.springframework.security: ${LOGGING_LEVEL_SECURITY:WARN}
    org.hibernate.SQL: ${LOGGING_LEVEL_SQL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_SQL_PARAMS:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOGGING_FILE:logs/senior-dev-academy.log}
    max-size: ${LOGGING_FILE_MAX_SIZE:10MB}
    max-history: ${LOGGING_FILE_MAX_HISTORY:30}
    
# Custom Application Properties
app:
  name: Senior Developer Academy
  version: 1.0.0
  description: The most comprehensive learning portal for senior developer preparation
  
  # Security settings - Externalized
  security:
    jwt:
      secret: ${JWT_SECRET}  # REQUIRED: Must be set via environment variable
      expiration: ${JWT_EXPIRATION:86400000}  # 24 hours default
      
  # File upload settings - Externalized
  upload:
    max-file-size: ${UPLOAD_MAX_FILE_SIZE:10MB}
    max-request-size: ${UPLOAD_MAX_REQUEST_SIZE:50MB}
    upload-dir: ${UPLOAD_DIR:./uploads}
    
  # Email configuration (for notifications) - Externalized
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}  # REQUIRED if email enabled
    password: ${MAIL_PASSWORD}  # REQUIRED if email enabled
    
  # External API configurations - Externalized
  external-apis:
    github:
      token: ${GITHUB_TOKEN:}
    stackoverflow:
      key: ${STACKOVERFLOW_KEY:}
      
  # Feature flags - Externalized
  features:
    code-execution: ${FEATURE_CODE_EXECUTION:true}
    ai-assistance: ${FEATURE_AI_ASSISTANCE:true}
    progress-analytics: ${FEATURE_PROGRESS_ANALYTICS:true}
    social-features: ${FEATURE_SOCIAL_FEATURES:false}
    
  # Performance settings - Externalized
  performance:
    monitoring-enabled: ${PERFORMANCE_MONITORING_ENABLED:true}
    slow-query-threshold: ${PERFORMANCE_SLOW_QUERY_THRESHOLD:1000}
    request-timeout: ${PERFORMANCE_REQUEST_TIMEOUT:30000}