-- Zero-Experience Learning Methodology Database Schema
-- This migration creates the comprehensive database structure for cognitive science-based learning

-- Learning methodology configuration
CREATE TABLE learning_methodology_config (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    methodology_name VARCHAR(255) NOT NULL,
    cognitive_science_principles TEXT, -- JSON array of principles
    amazon_competency_alignment TEXT, -- JSON mapping to L3-L6 levels
    multi_modal_support BOOLEAN DEFAULT true,
    adaptive_intelligence BOOLEAN DEFAULT true,
    effectiveness_metrics TEXT, -- JSON metrics tracking
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Cognitive learning components
CREATE TABLE cognitive_learning_components (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    component_type VARCHAR(100) NOT NULL, -- feynman, dual_coding, blooms, spaced_repetition
    implementation_details TEXT NOT NULL, -- JSON implementation specifics
    amazon_integration TEXT, -- JSON Amazon-specific integration
    effectiveness_metrics TEXT, -- JSON effectiveness tracking
    validation_criteria TEXT, -- JSON validation rules
    order_index INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Multi-modal content delivery
CREATE TABLE multi_modal_content (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content_id BIGINT NOT NULL, -- Reference to learning content
    content_type VARCHAR(100) NOT NULL, -- module, topic, question
    visual_component TEXT, -- JSON with diagrams, animations, infographics
    auditory_component TEXT, -- JSON with audio explanations, pronunciations
    kinesthetic_component TEXT, -- JSON with hands-on exercises, drag-drop
    reading_writing_component TEXT, -- JSON with documentation, notes, essays
    amazon_context_integration TEXT, -- JSON Amazon-specific examples
    effectiveness_score INTEGER DEFAULT 0, -- 0-100 effectiveness rating
    cognitive_load_level INTEGER DEFAULT 5, -- 1-10 cognitive complexity
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Amazon competency progression tracking
CREATE TABLE amazon_competency_progression (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    current_amazon_level VARCHAR(10) DEFAULT 'L3', -- L3, L4, L5, L6
    target_amazon_level VARCHAR(10) DEFAULT 'L5',
    competency_gaps TEXT, -- JSON array of skill gaps
    leadership_principles_progress TEXT, -- JSON mapping of 16 principles
    technical_competencies TEXT, -- JSON technical skills mapping
    behavioral_competencies TEXT, -- JSON behavioral skills mapping
    progression_timeline TEXT, -- JSON timeline with milestones
    interview_readiness_score INTEGER DEFAULT 0, -- 0-100 readiness score
    cultural_fit_score INTEGER DEFAULT 0, -- 0-100 Amazon culture alignment
    last_assessed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Learning style adaptation
CREATE TABLE learning_style_adaptation (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    detected_learning_style VARCHAR(50), -- visual, auditory, kinesthetic, reading_writing
    learning_style_confidence DECIMAL(5,2) DEFAULT 0.0, -- 0.0-1.0 confidence
    adaptation_accuracy DECIMAL(5,2) DEFAULT 0.0, -- 0.0-1.0 accuracy
    adaptation_speed INTEGER DEFAULT 5, -- interactions needed to detect
    personalization_settings TEXT, -- JSON personalization preferences
    amazon_cultural_alignment TEXT, -- JSON Amazon culture preferences
    multi_modal_preferences TEXT, -- JSON preferred learning modalities
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Cognitive load management
CREATE TABLE cognitive_load_management (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    current_cognitive_load INTEGER DEFAULT 5, -- 1-10 scale
    optimal_load_threshold INTEGER DEFAULT 7, -- personalized threshold
    complexity_adjustment_factor DECIMAL(3,2) DEFAULT 1.0, -- adjustment multiplier
    break_recommendations TEXT, -- JSON break schedule recommendations
    learning_fatigue_indicators TEXT, -- JSON fatigue detection metrics
    amazon_pace_alignment TEXT, -- JSON Amazon learning pace preferences
    overload_prevention_active BOOLEAN DEFAULT true,
    last_calculated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Feynman Technique implementation tracking
CREATE TABLE feynman_technique_implementations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content_id BIGINT NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    simple_explanation TEXT NOT NULL, -- Child-friendly explanation
    knowledge_gaps TEXT, -- JSON array of identified gaps
    source_reinforcement TEXT, -- JSON reinforcement materials
    simplification_analogies TEXT, -- JSON array of analogies
    amazon_scale_context TEXT, -- JSON Amazon-specific context
    understanding_validation TEXT, -- JSON validation criteria
    iteration_count INTEGER DEFAULT 1,
    mastery_achieved BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Dual Coding Theory application
CREATE TABLE dual_coding_applications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content_id BIGINT NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    visual_information TEXT, -- JSON visual processing elements
    verbal_information TEXT, -- JSON verbal processing elements
    spatial_relationships TEXT, -- JSON spatial visualization
    temporal_sequences TEXT, -- JSON process flow sequences
    integration_effectiveness INTEGER DEFAULT 0, -- 0-100 effectiveness
    amazon_architecture_examples TEXT, -- JSON Amazon system examples
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bloom's Taxonomy progression tracking
CREATE TABLE blooms_taxonomy_progression (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    content_id BIGINT NOT NULL,
    remember_level_score INTEGER DEFAULT 0, -- 0-100 score
    understand_level_score INTEGER DEFAULT 0,
    apply_level_score INTEGER DEFAULT 0,
    analyze_level_score INTEGER DEFAULT 0,
    evaluate_level_score INTEGER DEFAULT 0,
    create_level_score INTEGER DEFAULT 0,
    current_level VARCHAR(20) DEFAULT 'remember',
    amazon_competency_alignment VARCHAR(10), -- L3, L4, L5, L6
    progression_evidence TEXT, -- JSON evidence of progression
    next_level_requirements TEXT, -- JSON requirements for next level
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Spaced repetition scheduling
CREATE TABLE spaced_repetition_schedule (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    content_id BIGINT NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    repetition_interval INTEGER DEFAULT 1, -- days until next review
    ease_factor DECIMAL(3,2) DEFAULT 2.5, -- spaced repetition ease factor
    repetition_count INTEGER DEFAULT 0,
    last_reviewed TIMESTAMP,
    next_review_date TIMESTAMP,
    retention_score INTEGER DEFAULT 0, -- 0-100 retention measurement
    amazon_interview_priority BOOLEAN DEFAULT false,
    difficulty_adjustment DECIMAL(3,2) DEFAULT 1.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Visual learning components for optimization
CREATE TABLE visual_learning_components (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content_id BIGINT NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    component_type VARCHAR(50) NOT NULL, -- ALGORITHM_ANIMATION, INFOGRAPHIC, MIND_MAP, etc.
    title VARCHAR(300) NOT NULL,
    description TEXT,
    complexity_level VARCHAR(20) DEFAULT 'BEGINNER', -- BEGINNER, INTERMEDIATE, ADVANCED, EXPERT
    visual_data TEXT, -- JSON data for visual rendering
    interactive_elements TEXT, -- JSON configuration for interactive elements
    animation_config TEXT, -- JSON configuration for animations
    amazon_context TEXT, -- JSON Amazon-specific context
    effectiveness_score INTEGER DEFAULT 0, -- 0-100 effectiveness rating
    cognitive_load_level INTEGER DEFAULT 5, -- 1-10 cognitive complexity
    accessibility_features TEXT, -- JSON accessibility features
    mobile_optimized BOOLEAN DEFAULT false,
    view_count BIGINT DEFAULT 0,
    average_view_duration INTEGER DEFAULT 0, -- seconds
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance optimization
CREATE INDEX idx_multi_modal_content_id ON multi_modal_content(content_id, content_type);
CREATE INDEX idx_visual_learning_content ON visual_learning_components(content_id, content_type);
CREATE INDEX idx_visual_learning_type ON visual_learning_components(component_type);
CREATE INDEX idx_visual_learning_complexity ON visual_learning_components(complexity_level);
CREATE INDEX idx_visual_learning_effectiveness ON visual_learning_components(effectiveness_score);
CREATE INDEX idx_amazon_competency_user ON amazon_competency_progression(user_id);
CREATE INDEX idx_learning_style_user ON learning_style_adaptation(user_id);
CREATE INDEX idx_cognitive_load_user ON cognitive_load_management(user_id);
CREATE INDEX idx_feynman_content ON feynman_technique_implementations(content_id, content_type);
CREATE INDEX idx_dual_coding_content ON dual_coding_applications(content_id, content_type);
CREATE INDEX idx_blooms_user_content ON blooms_taxonomy_progression(user_id, content_id);
CREATE INDEX idx_spaced_repetition_user ON spaced_repetition_schedule(user_id);
CREATE INDEX idx_spaced_repetition_next_review ON spaced_repetition_schedule(next_review_date);

-- Insert initial cognitive science methodology configuration
INSERT INTO learning_methodology_config (
    methodology_name,
    cognitive_science_principles,
    amazon_competency_alignment,
    multi_modal_support,
    adaptive_intelligence
) VALUES (
    'Zero-Experience to Amazon Senior SDE',
    '["Feynman Technique", "Dual Coding Theory", "Blooms Taxonomy", "Spaced Repetition", "Cognitive Load Theory"]',
    '{"L3": "Junior SDE", "L4": "SDE", "L5": "Senior SDE", "L6": "Principal SDE"}',
    true,
    true
);

-- Insert core cognitive learning components
INSERT INTO cognitive_learning_components (component_type, implementation_details, amazon_integration, order_index) VALUES
('feynman', '{"simple_explanation": true, "gap_identification": true, "iterative_simplification": true}', '{"amazon_analogies": true, "scale_context": true}', 1),
('dual_coding', '{"visual_processing": true, "verbal_processing": true, "spatial_visualization": true}', '{"architecture_diagrams": true, "system_examples": true}', 2),
('blooms', '{"progressive_complexity": true, "prerequisite_checking": true, "competency_validation": true}', '{"l3_l6_alignment": true, "hiring_bar_standards": true}', 3),
('spaced_repetition', '{"optimized_scheduling": true, "retention_tracking": true, "adaptive_intervals": true}', '{"interview_preparation": true, "amazon_patterns": true}', 4);